Repository minio/minio-rs, pull requests merged in 2025-05, with the labels that each got.

#152 fixed incorrect renaming of listen_bucket_notification
  src/s3/builders.rs
  src/s3/builders/listen_bucket_notification.rs
  src/s3/client.rs
  src/s3/client/listen_bucket_notification.rs
  src/s3/response.rs
  src/s3/response/listen_bucket_notification.rs
  tests/test_listen_bucket_notification.rs
Labels: enhancement

#153 Fixed xml parsing of bucket_lifecycle, added support for with_updated_at
  common/src/example.rs
  examples/bucket_lifecycle.rs
  src/s3/builders/get_bucket_lifecycle.rs
  src/s3/builders/put_bucket_lifecycle.rs
  src/s3/client/put_bucket_lifecycle.rs
  src/s3/error.rs
  src/s3/lifecycle_config.rs
  src/s3/mod.rs
  src/s3/response/get_bucket_lifecycle.rs
  src/s3/types.rs
  tests/test_bucket_lifecycle.rs
Labels: bug

#156 Release v0.2.0
  Cargo.toml
Labels: enhancement

#159 Update the README with additional information
  README.md
Labels: documentation, enhancement

#158 Added several tests to test_append_object
  src/s3/error.rs
  src/s3/response/get_bucket_lifecycle.rs
  tests/test_append_object.rs
Labels: enhancement
